import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/ui/Sidebar";
import Topbar from "@/components/ui/TopBar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} text-zinc-900 h-full antialiased `}
        >
            <body className="min-h-full flex flex-col">
                <div className="flex flex-1 justify-between">
                    <Sidebar />
                    <main className="flex flex-col w-full">
                        <Topbar />
                        <div className="p-8">{children}</div>
                    </main>
                </div>
            </body>
        </html>
    );
}
